#!/usr/bin/env python3

from __future__ import annotations

import json
import plistlib
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIREBASE_CONFIG_PATH = ROOT / "firebase.json"


def run_firebase(*args: str) -> str:
    command = ["firebase", *args]
    result = subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
      raise SystemExit(
          f"Firebase CLI failed:\n$ {' '.join(command)}\n\n{result.stderr.strip()}"
      )
    return result.stdout


def extract_json(output: str) -> dict:
    start = output.find("{")
    end = output.rfind("}")
    if start == -1 or end == -1:
        raise ValueError(f"Expected JSON output, got:\n{output}")
    return json.loads(output[start : end + 1])


def extract_plist_text(output: str) -> str:
    start = output.find("<?xml")
    if start == -1:
        raise ValueError(f"Expected plist output, got:\n{output}")
    return output[start:].strip() + "\n"


def write_text(relative_path: str, content: str) -> None:
    path = ROOT / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"Updated {path.relative_to(ROOT)}")


def write_json(relative_path: str, payload: dict) -> None:
    write_text(relative_path, json.dumps(payload, indent=2) + "\n")


def android_config_for_app(full_config: dict, app_id: str, package_name: str) -> dict:
    for client in full_config["client"]:
        client_info = client.get("client_info", {})
        android_info = client_info.get("android_client_info", {})
        if (
            client_info.get("mobilesdk_app_id") == app_id
            and android_info.get("package_name") == package_name
        ):
            return {
                "project_info": full_config["project_info"],
                "client": [client],
                "configuration_version": full_config["configuration_version"],
            }
    raise KeyError(
        f"Android Firebase app {app_id} / {package_name} was not found in the downloaded sdk config."
    )


def render_firebase_options(
    *,
    project_id: str,
    project_number: str,
    web_config: dict,
    android_mt: dict,
    android_rw: dict,
    ios_mt: dict,
    ios_rw: dict,
) -> str:
    android_mt_client = android_mt["client"][0]
    android_rw_client = android_rw["client"][0]

    return f"""// File generated by scripts/sync_firebase_configs.py.
// Firebase project: {project_id}
// Project number: {project_number}

import 'package:core_pkg/config/country_runtime.dart';
import 'package:core_pkg/constants/enums.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {{
  /// Returns `true` when the current platform has a real (non-placeholder)
  /// Firebase configuration available.
  static bool get hasCurrentPlatformConfig {{
    try {{
      final opts = currentPlatform;
      return !_isPlaceholder(opts.apiKey) && !_isPlaceholder(opts.appId);
    }} catch (_) {{
      return false;
    }}
  }}

  static FirebaseOptions get currentPlatform {{
    if (kIsWeb) {{
      return web;
    }}
    final country = CountryRuntime.config.country;
    switch (defaultTargetPlatform) {{
      case TargetPlatform.android:
        return androidForCountry(country);
      case TargetPlatform.iOS:
        return iosForCountry(country);
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${{defaultTargetPlatform.name}}. Use FirebaseRuntimeService '
          'for platform-safe initialization.',
        );
    }}
  }}

  static FirebaseOptions androidForCountry(Country country) {{
    return switch (country) {{
      Country.rw => androidRw,
      Country.mt => androidMt,
    }};
  }}

  static FirebaseOptions iosForCountry(Country country) {{
    return switch (country) {{
      Country.rw => iosRw,
      Country.mt => iosMt,
    }};
  }}

  static bool _isPlaceholder(String value) {{
    return value.trim().isEmpty || value.contains('REPLACE_WITH_ACTUAL_');
  }}

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '{web_config["apiKey"]}',
    appId: '{web_config["appId"]}',
    messagingSenderId: '{web_config["messagingSenderId"]}',
    projectId: '{web_config["projectId"]}',
    authDomain: '{web_config["authDomain"]}',
    storageBucket: '{web_config["storageBucket"]}',
    measurementId: '{web_config["measurementId"]}',
  );

  static const FirebaseOptions androidMt = FirebaseOptions(
    apiKey: '{android_mt_client["api_key"][0]["current_key"]}',
    appId: '{android_mt_client["client_info"]["mobilesdk_app_id"]}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{android_mt["project_info"]["storage_bucket"]}',
  );

  static const FirebaseOptions androidRw = FirebaseOptions(
    apiKey: '{android_rw_client["api_key"][0]["current_key"]}',
    appId: '{android_rw_client["client_info"]["mobilesdk_app_id"]}',
    messagingSenderId: '{project_number}',
    projectId: '{project_id}',
    storageBucket: '{android_rw["project_info"]["storage_bucket"]}',
  );

  static const FirebaseOptions iosMt = FirebaseOptions(
    apiKey: '{ios_mt["API_KEY"]}',
    appId: '{ios_mt["GOOGLE_APP_ID"]}',
    messagingSenderId: '{ios_mt["GCM_SENDER_ID"]}',
    projectId: '{ios_mt["PROJECT_ID"]}',
    storageBucket: '{ios_mt["STORAGE_BUCKET"]}',
    iosBundleId: '{ios_mt["BUNDLE_ID"]}',
  );

  static const FirebaseOptions iosRw = FirebaseOptions(
    apiKey: '{ios_rw["API_KEY"]}',
    appId: '{ios_rw["GOOGLE_APP_ID"]}',
    messagingSenderId: '{ios_rw["GCM_SENDER_ID"]}',
    projectId: '{ios_rw["PROJECT_ID"]}',
    storageBucket: '{ios_rw["STORAGE_BUCKET"]}',
    iosBundleId: '{ios_rw["BUNDLE_ID"]}',
  );
}}
"""


def main() -> int:
    firebase_config = json.loads(FIREBASE_CONFIG_PATH.read_text(encoding="utf-8"))
    dinein = firebase_config["dinein"]
    project_id = dinein["projectId"]
    project_number = dinein["projectNumber"]
    flavors = dinein["flavors"]

    android_source_app_id = flavors["mt"]["android"]["appId"]
    android_full = extract_json(
        run_firebase(
            "apps:sdkconfig",
            "android",
            android_source_app_id,
            "--project",
            project_id,
        )
    )

    android_mt = android_config_for_app(
        android_full,
        flavors["mt"]["android"]["appId"],
        flavors["mt"]["android"]["applicationId"],
    )
    android_rw = android_config_for_app(
        android_full,
        flavors["rw"]["android"]["appId"],
        flavors["rw"]["android"]["applicationId"],
    )

    write_json(flavors["mt"]["android"]["fileOutput"], android_mt)
    write_json(flavors["rw"]["android"]["fileOutput"], android_rw)
    write_json(
        firebase_config["flutter"]["platforms"]["android"]["default"]["fileOutput"],
        android_mt,
    )

    ios_outputs: dict[str, dict] = {}
    for flavor_name, flavor_meta in flavors.items():
        plist_text = extract_plist_text(
            run_firebase(
                "apps:sdkconfig",
                "ios",
                flavor_meta["ios"]["appId"],
                "--project",
                project_id,
            )
        )
        write_text(flavor_meta["ios"]["fileOutput"], plist_text)
        ios_outputs[flavor_name] = plistlib.loads(plist_text.encode("utf-8"))

    mt_default_plist = extract_plist_text(
        run_firebase(
            "apps:sdkconfig",
            "ios",
            firebase_config["flutter"]["platforms"]["ios"]["default"]["appId"],
            "--project",
            project_id,
        )
    )
    write_text(firebase_config["flutter"]["platforms"]["ios"]["default"]["fileOutput"], mt_default_plist)

    web_config = extract_json(
        run_firebase(
            "apps:sdkconfig",
            "web",
            dinein["web"]["appId"],
            "--project",
            project_id,
        )
    )

    firebase_options = render_firebase_options(
        project_id=project_id,
        project_number=project_number,
        web_config=web_config,
        android_mt=android_mt,
        android_rw=android_rw,
        ios_mt=ios_outputs["mt"],
        ios_rw=ios_outputs["rw"],
    )
    write_text("lib/firebase_options.dart", firebase_options)

    print("Firebase configs are aligned with the live project.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
