// File generated by scripts/sync_firebase_configs.py.
// Firebase project: gen-lang-client-0172279957
// Project number: 1074154147498

import 'package:core_pkg/config/country_runtime.dart';
import 'package:core_pkg/constants/enums.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  /// Returns `true` when the current platform has a real (non-placeholder)
  /// Firebase configuration available.
  static bool get hasCurrentPlatformConfig {
    try {
      final opts = currentPlatform;
      return !_isPlaceholder(opts.apiKey) && !_isPlaceholder(opts.appId);
    } catch (_) {
      return false;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    final country = CountryRuntime.config.country;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidForCountry(country);
      case TargetPlatform.iOS:
        return iosForCountry(country);
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${defaultTargetPlatform.name}. Use FirebaseRuntimeService '
          'for platform-safe initialization.',
        );
    }
  }

  static FirebaseOptions androidForCountry(Country country) {
    return switch (country) {
      Country.rw => androidRw,
      Country.mt => androidMt,
    };
  }

  static FirebaseOptions iosForCountry(Country country) {
    return switch (country) {
      Country.rw => iosRw,
      Country.mt => iosMt,
    };
  }

  static bool _isPlaceholder(String value) {
    return value.trim().isEmpty || value.contains('REPLACE_WITH_ACTUAL_');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANrlSIDdY30yGkvmrmZaDYOoSCmWc7ZlM',
    appId: '1:1074154147498:web:40ff2d11ccfa7d2cdc4ad3',
    messagingSenderId: '1074154147498',
    projectId: 'gen-lang-client-0172279957',
    authDomain: 'gen-lang-client-0172279957.firebaseapp.com',
    storageBucket: 'gen-lang-client-0172279957.firebasestorage.app',
    measurementId: 'G-ZB65WBPLJ4',
  );

  static const FirebaseOptions androidMt = FirebaseOptions(
    apiKey: 'AIzaSyBZWg0JT-v2Qpirp63RbsPqzB4JY2onfJw',
    appId: '1:1074154147498:android:1dd401b016b8c501dc4ad3',
    messagingSenderId: '1074154147498',
    projectId: 'gen-lang-client-0172279957',
    storageBucket: 'gen-lang-client-0172279957.firebasestorage.app',
  );

  static const FirebaseOptions androidRw = FirebaseOptions(
    apiKey: 'AIzaSyBZWg0JT-v2Qpirp63RbsPqzB4JY2onfJw',
    appId: '1:1074154147498:android:cbd8a51892a2ee93dc4ad3',
    messagingSenderId: '1074154147498',
    projectId: 'gen-lang-client-0172279957',
    storageBucket: 'gen-lang-client-0172279957.firebasestorage.app',
  );

  static const FirebaseOptions iosMt = FirebaseOptions(
    apiKey: 'AIzaSyC3wczTXHP3fkryFydOTu6RIbxZ5vRUbg0',
    appId: '1:1074154147498:ios:f9338408dab88c45dc4ad3',
    messagingSenderId: '1074154147498',
    projectId: 'gen-lang-client-0172279957',
    storageBucket: 'gen-lang-client-0172279957.firebasestorage.app',
    iosBundleId: 'com.dineinmalta.app',
  );

  static const FirebaseOptions iosRw = FirebaseOptions(
    apiKey: 'AIzaSyC8dE6DUHuVTK9tFkNx31EcEqNeNogUpjw',
    appId: '1:1074154147498:ios:a44ce46db3c51bfcdc4ad3',
    messagingSenderId: '1074154147498',
    projectId: 'gen-lang-client-0172279957',
    storageBucket: 'gen-lang-client-0172279957.firebasestorage.app',
    iosBundleId: 'com.dineinrw.app',
  );
}
